In [2]:
# Importamos lo esencial una sola vez
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

# Configuración estética para los gráficos
sns.set_theme(style='whitegrid', palette='deep')
plt.rcParams['figure.figsize'] = (9, 5)
pd.set_option('display.max_columns', 30)
np.random.seed(42)

## Carga de Datos y Formatos

In [3]:
# Carga de datos
df = pd.read_csv('data\\national_history.csv')
# Forma del Dataset
print(f'Nº de filas: {df.shape[0]}')
print(f'Nº de columnas: {df.shape[1]}')
# Muestreo
df.head()

Nº de filas: 420
Nº de columnas: 17

,date,death,deathIncrease,inIcuCumulative,inIcuCurrently,hospitalizedIncrease,hospitalizedCurrently,hospitalizedCumulative,negative,negativeIncrease,onVentilatorCumulative,onVentilatorCurrently,positive,positiveIncrease,states,totalTestResults,totalTestResultsIncrease
0,2021-03-07,515151.0,842,45475.0,8134.0,726,40199.0,776361.0,74582825.0,131835,4281.0,2802.0,28756489.0,41835,56,363825123,1170059
1,2021-03-06,514309.0,1680,45453.0,8409.0,503,41401.0,775635.0,74450990.0,143835,4280.0,2811.0,28714654.0,60015,56,362655064,1430992
2,2021-03-05,512629.0,2221,45373.0,8634.0,2781,42541.0,775132.0,74307155.0,271917,4275.0,2889.0,28654639.0,68787,56,361224072,1744417
3,2021-03-04,510408.0,1743,45293.0,8970.0,1530,44172.0,772351.0,74035238.0,177957,4267.0,2973.0,28585852.0,65487,56,359479655,1590984
4,2021-03-03,508665.0,2449,45214.0,9359.0,2172,45462.0,770821.0,73857281.0,267001,4260.0,3094.0,28520365.0,66836,56,357888671,1406795

In [ ]:
for col in df.columns:
    if col == 'date':
        continue
    print(f'{df[col].value_counts().sort_index()}\n')

death
0.0         16
2.0          2
4.0          1
5.0          1
8.0          1
            ..
508665.0     1
510408.0     1
512629.0     1
514309.0     1
515151.0     1
Name: count, Length: 376, dtype: int64

deathIncrease
0       45
1        2
2        4
3        3
4        3
        ..
4079     1
4087     1
4409     1
5212     1
5427     1
Name: count, Length: 344, dtype: int64

inIcuCumulative
74.0       1
91.0       1
124.0      1
140.0      1
156.0      1
          ..
45214.0    1
45293.0    1
45373.0    1
45453.0    1
45475.0    1
Name: count, Length: 348, dtype: int64

inIcuCurrently
1299.0     1
1792.0     1
2174.0     1
2456.0     1
3087.0     1
          ..
23821.0    1
23857.0    1
23881.0    1
23891.0    1
23912.0    1
Name: count, Length: 345, dtype: int64

hospitalizedIncrease
-2858      1
-752       1
 0        54
 1         2
 3         2
          ..
 6652      1
 6683      1
 7994      1
 9055      1
 17155     1
Name: count, Length: 347, dtype: int64

hospitalizedCurrently
325.0       1
416.0       1
617.0       1
1042.0      1
1492.0      1
           ..
131195.0    1
131326.0    1
131921.0    1
132370.0    1
132474.0    1
Name: count, Length: 356, dtype: int64

hospitalizedCumulative
4.0         1
5.0         1
6.0         3
9.0         2
12.0        1
           ..
770821.0    1
772351.0    1
775132.0    1
775635.0    1
776361.0    1
Name: count, Length: 366, dtype: int64

negative
2.0           1
3.0           1
5.0           1
581.0         1
713.0         1
             ..
73857281.0    1
74035238.0    1
74307155.0    1
74450990.0    1
74582825.0    1
Name: count, Length: 372, dtype: int64

negativeIncrease
-658774     1
-213981     1
 0         48
 1          1
 2          2
           ..
 443993     1
 448167     1
 450795     1
 456078     1
 480256     1
Name: count, Length: 372, dtype: int64

onVentilatorCumulative
32.0      2
39.0      7
43.0      1
152.0     1
158.0     2
         ..
4260.0    1
4267.0    1
4275.0    1
4280.0    1
4281.0    1
Name: count, Length: 321, dtype: int64

onVentilatorCurrently
167.0     1
258.0     1
293.0     1
390.0     1
433.0     1
         ..
7946.0    1
7948.0    1
7976.0    1
7990.0    1
8004.0    1
Name: count, Length: 332, dtype: int64

positive
0.0            5
1.0            2
2.0           13
3.0            3
5.0            7
              ..
28520365.0     1
28585852.0     1
28654639.0     1
28714654.0     1
28756489.0     1
Name: count, Length: 386, dtype: int64

positiveIncrease
0         35
1          9
2          3
3          1
24         1
          ..
250184     1
269368     1
272043     1
280318     1
295121     1
Name: count, Length: 375, dtype: int64

states
1       9
2       5
3       2
4      12
5       5
6      12
7       2
8       1
11      1
12      1
16      1
26      1
32      1
40      1
51      9
56    357
Name: count, dtype: int64

totalTestResults
0            9
1            1
2            4
3            2
5            2
            ..
357888671    1
359479655    1
361224072    1
362655064    1
363825123    1
Name: count, Length: 398, dtype: int64

totalTestResultsIncrease
0          23
1          13
2           4
3           3
4           2
           ..
2140465     1
2146223     1
2193466     1
2302086     1
2309884     1
Name: count, Length: 380, dtype: int64

### No hay variables categóricas

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      420 non-null    str
 1   death                     392 non-null    float64
 2   deathIncrease             420 non-null    int64
 3   inIcuCumulative           348 non-null    float64
 4   inIcuCurrently            347 non-null    float64
 5   hospitalizedIncrease      420 non-null    int64
 6   hospitalizedCurrently     356 non-null    float64
 7   hospitalizedCumulative    369 non-null    float64
 8   negative                  372 non-null    float64
 9   negativeIncrease          420 non-null    int64
 10  onVentilatorCumulative    341 non-null    float64
 11  onVentilatorCurrently     348 non-null    float64
 12  positive                  419 non-null    float64
 13  positiveIncrease          420 non-null    int64
 14  states                    420 non-null    int64
 15  totalTestResults          420 non-null    int64
 16  totalTestResultsIncrease  420 non-null    int64
dtypes: float64(9), int64(7), str(1)
memory usage: 55.9 KB

In [7]:
print('Valores duplicados por columna')
df.duplicated().sum()

Valores duplicados por columna

np.int64(0)

In [8]:
print('Nº de valores Nulos por columna:')
df.isnull().sum()

Nº de valores Nulos por columna:

date                         0
death                       28
deathIncrease                0
inIcuCumulative             72
inIcuCurrently              73
hospitalizedIncrease         0
hospitalizedCurrently       64
hospitalizedCumulative      51
negative                    48
negativeIncrease             0
onVentilatorCumulative      79
onVentilatorCurrently       72
positive                     1
positiveIncrease             0
states                       0
totalTestResults             0
totalTestResultsIncrease     0
dtype: int64

In [9]:
print('% de valores nulos por columna')
df.isnull().sum() / len(df) * 100

% de valores nulos por columna

date                         0.000000
death                        6.666667
deathIncrease                0.000000
inIcuCumulative             17.142857
inIcuCurrently              17.380952
hospitalizedIncrease         0.000000
hospitalizedCurrently       15.238095
hospitalizedCumulative      12.142857
negative                    11.428571
negativeIncrease             0.000000
onVentilatorCumulative      18.809524
onVentilatorCurrently       17.142857
positive                     0.238095
positiveIncrease             0.000000
states                       0.000000
totalTestResults             0.000000
totalTestResultsIncrease     0.000000
dtype: float64

In [10]:
df.describe()

,death,deathIncrease,inIcuCumulative,inIcuCurrently,hospitalizedIncrease,hospitalizedCurrently,hospitalizedCumulative,negative,negativeIncrease,onVentilatorCumulative,onVentilatorCurrently,positive,positiveIncrease,states,totalTestResults,totalTestResultsIncrease
count,392.000000,420.000000,348.000000,347.000000,420.000000,356.000000,369.000000,3.720000e+02,420.000000,341.000000,348.000000,4.190000e+02,420.000000,420.000000,4.200000e+02,4.200000e+02
mean,187210.668367,1226.550000,21059.344828,12059.227666,1848.478571,57987.117978,310817.140921,3.030351e+07,177578.154762,2173.932551,3975.298851,8.116687e+06,68467.830952,49.476190,1.073369e+08,8.662503e+05
std,142331.657380,1070.129644,13572.638376,5668.415483,1708.460481,31898.555998,235557.870159,2.407815e+07,121544.473208,1327.372196,2191.080602,8.967432e+06,68682.221496,16.896764,1.129172e+08,6.579460e+05
min,0.000000,0.000000,74.000000,1299.000000,-2858.000000,325.000000,4.000000,2.000000e+00,-658774.000000,32.000000,167.000000,0.000000e+00,0.000000,1.000000,0.000000e+00,0.000000e+00
25%,86911.750000,439.750000,9900.250000,7495.500000,765.750000,35100.500000,123250.000000,6.753778e+06,79236.750000,951.000000,2168.500000,1.004386e+06,22462.500000,56.000000,5.888598e+06,2.388558e+05
50%,169118.500000,1016.000000,18797.500000,10114.000000,1490.000000,48811.000000,280138.000000,2.757246e+07,206620.000000,2107.000000,3186.500000,5.044337e+06,44664.500000,56.000000,6.839699e+07,8.223685e+05
75%,258912.250000,1642.500000,32998.500000,15596.500000,2467.000000,70519.250000,481309.000000,5.084301e+07,260621.000000,3430.000000,5828.500000,1.234137e+07,89684.250000,56.000000,1.854937e+08,1.401706e+06
max,515151.000000,5427.000000,45475.000000,23912.000000,17155.000000,132474.000000,776361.000000,7.458282e+07,480256.000000,4281.000000,8004.000000,2.875649e+07,295121.000000,56.000000,3.638251e+08,2.309884e+06

In [11]:
df.describe(include='str')

              date
count          420
unique         420
top     2021-03-07
freq             1

In [12]:
# Convertimos la columna date a formato fecha
df['date'] = pd.to_datetime(df['date'])

In [13]:
df['date'].head()

0   2021-03-07
1   2021-03-06
2   2021-03-05
3   2021-03-04
4   2021-03-03
Name: date, dtype: datetime64[us]

In [14]:
# Imputación provisional de los valores nulos

In [15]:
for col in df.columns:
    if col == 'date' or df[col].dtype == 'int64':
        continue
    df[col] = df[col].astype('Int64')

In [16]:
df.dtypes

date                        datetime64[us]
death                                Int64
deathIncrease                        int64
inIcuCumulative                      Int64
inIcuCurrently                       Int64
hospitalizedIncrease                 int64
hospitalizedCurrently                Int64
hospitalizedCumulative               Int64
negative                             Int64
negativeIncrease                     int64
onVentilatorCumulative               Int64
onVentilatorCurrently                Int64
positive                             Int64
positiveIncrease                     int64
states                               int64
totalTestResults                     int64
totalTestResultsIncrease             int64
dtype: object

In [29]:
df.isnull().sum()

date                         0
death                       28
deathIncrease                0
inIcuCumulative             72
inIcuCurrently              73
hospitalizedIncrease         0
hospitalizedCurrently       64
hospitalizedCumulative      51
negative                    48
negativeIncrease             0
onVentilatorCumulative      79
onVentilatorCurrently       72
positive                     1
positiveIncrease             0
states                       0
totalTestResults             0
totalTestResultsIncrease     0
dtype: int64